---
abstract: 'A Module::Install extension that provides an alternate way to specify dependencies'
author:
  - 'Robert Krimen <robertkrimen@gmail.com>'
build_requires:
  File::Spec: 0
  Test::Most: 0
  YAML::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Install-ParseRequires
requires:
  Module::Install: 0.85
version: 0.002
